#!/usr/bin/python3

import argparse

try:
    from wstools import ldmlfonts
except ImportError:
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'lib', 'wstools')))
    from wstools import ldmlfonts


def main():
    parser = argparse.ArgumentParser(description='Populate font information to LDML files')
    parser.add_argument('datafile', help='CSV file export from Google Sheet document Script2Font')
    parser.add_argument('--version', action='version', version='%(prog)s: 0.1')
    args = parser.parse_args()

    ldmlfonts.read_font_data(args.datafile)
    for tag, font in ldmlfonts.suggestions.items():
        print(f'{tag}: {font}')


if __name__ == '__main__':
    main()
